Airvibes2/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airvibes2.Models;

namespace Airvibes2.Controllers
{
    public class ArtistsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Records
        public ActionResult Index()
        {
            var artists = db.Artists.ToList().OrderBy(m => m.Id);
            return View(artists);
        }

        // GET: Records/Details/5
        public ActionResult Details(int? id)
        {
            var context = new ApplicationDbContext();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Artists artists = db.Artists.Find(id);

            if (artists == null)
            {
                return HttpNotFound();
            }
            ViewBag.Photo = artists.Photo;
            ViewBag.Name = artists.Name;
            ViewBag.Bio = artists.Bio;
            artists.Records = context.Records.Where(r => r.Artists_Id == artists.Id).ToList();
            context.SaveChanges();
            return View(artists);
        }
    }
}

Airvibes2/Controllers/RecordsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Airvibes2.Models;

namespace Airvibes2.Controllers
{
    public class RecordsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Records
        public ActionResult Index()
        {
            var records = db.Records.ToList().OrderBy(m=>m.Artists_Id);
            return View(records);
        }

        // GET: Records/Details/5
        public ActionResult Details(int? id)
        {
            var context = new ApplicationDbContext();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Records records = db.Records.Find(id);
            
            if (records == null)
            {
                return HttpNotFound();
            }


            ViewBag.Cover = records.Cover;
            ViewBag.Title = records.Title;
            ViewBag.Genre = records.Genre;
            ViewBag.ReleaseDate = records.ReleaseDate;
            ViewBag.ArtistId = context.Artists.Where(a => a.Id == records.Artists_Id).First().Id;
            ViewBag.Artist = context.Artists.Where(a => a.Id == records.Artists_Id).First().Name ;

            var vm = new List<CommentaireChansons>();
            foreach (var item in context.Songs.Where(s=>s.Records_Id == records.Id))
            {
                CommentaireChansons vm2 = new CommentaireChansons();
                vm2.Songs = item;
                vm2.SComment = context.SComment.Where(c => c.Songs_Id == item.Id).ToList();
                foreach (var item2 in vm2.SComment)
                {
                    item2.User = context.Users.Where(u => u.UserName == item2.Users_Id).FirstOrDefault();
                }
                vm.Add(vm2);
            }

            context.SaveChanges();
            return View("Details", vm);
        }
    }
}

Airvibes2/Controllers/SearchController.cs
using Airvibes2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Airvibes2.Controllers
{
    public class SearchController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Search
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SearchResult(string searchString)
        {
            var context = new ApplicationDbContext();
            SearchModel res = new SearchModel();
            res.Artists = db.Artists.Where(a => a.Name.ToLower().Contains(searchString.ToLower())).ToList();
            res.Records = db.Records.Where(a => a.Title.ToLower().Contains(searchString.ToLower())).ToList();
            res.Songs = db.Songs.Where(a => a.Title.ToLower().Contains(searchString.ToLower())).ToList();
            return View("SearchResults",res);
        }
    }
}

Airvibes2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Airvibes</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Airvibes", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Artistes", "Index", "Artists")</li>
                    <li>@Html.ActionLink("Albums", "Index", "Records")</li>
                    <li>
                        @using (Html.BeginForm("SearchResult", "Search"))
                        {
                            @Html.TextBox("searchString", null , new { @style = " -webkit-border-radius: 5px; - moz - border - radius: 5px; border - radius: 5px; background-color : #cccccc; height: 31px; margin-top : 9px; margin-left : 20px; font-size : 15px" })
                                        <input type="submit" value="Search" style="-webkit-border-radius: 5px; - moz - border - radius: 5px; border - radius: 5px; background-color : #cccccc; height: 31px;font-size : 15px"/>
                        }
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>


</body>
</html>